name: Java CI with Gradle

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    env:
      DISPLAY: ":99.0" # Définit un affichage pour Xvfb

    services:
      xvfb:
        image: selenium/standalone-chrome:latest
        options: -e VNC_SERVER=true -e VNC_PORT=5900

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Start Xvfb
        run: Xvfb $DISPLAY -ac -screen 0 1600x1200x24 > /dev/null 2>&1 &

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4.0.0
        with:
          gradle-version: '8.10'
      
      - name: Run tests with Gradle
        run: gradle test --no-daemon
      
      - name: Publish Test Report
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: build/reports/tests/

      # Étape ajoutée : Télécharger et installer PMD v4
      - name: Download PMD v4
        run: |
          wget https://github.com/pmd/pmd/releases/download/pmd_releases%2Fv4.3.0/pmd-bin-4.3.0.zip
          unzip pmd-bin-4.3.0.zip
          sudo mv pmd-bin-4.3.0 /opt/pmd

      # Étape ajoutée : Exécuter l'analyse PMD avec PMD v4
      - name: Run PMD static code analysis with PMD v4
        run: |
          /opt/pmd/bin/pmd -d src -R rulesets/java/quickstart.xml -f sarif -r pmd-report.sarif

      # Étape ajoutée : Télécharger le rapport PMD
      - name: Upload PMD Report
        uses: actions/upload-artifact@v4
        with:
          name: pmd-report  # Nom valide sans espaces ni caractères spéciaux
          path: pmd-report.sarif  # Assurez-vous que le chemin correspond au fichier généré par PMD

      - name: List files in workspace
        run: ls -R
